algoritmo "Media dos valores"

var
  P1, P2, T, final: real

inicio

    escreval("Programa pra calcular a media")
    escreval("------------------------------")
    escreva("Digite o valor da primeira nota: ")
    leia(P1)
    escreva("DIgite o valor da segunda nota: ")
    leia(P2)
    escreva("Digite o valor do trabalho: ")
    leia(T)
    final <- (P1 + P2 + T) / 3 

    escreva("A sua media foi ",final)

  

fimalgoritmo

